version: "3"

services:
  hadoop:
    hostname: hadoop
    container_name: hadoop
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "9095:9095"
      - "2181:2181"
      - "16010:16010"
      - "8088:8088"
      - "9000:9000"
      - "8032:8032"
      - "9870:9870"
      - "8042:8042"

    volumes:
      - ./database/hdfs:/hdfs

  hbase-client:
    build:
      context: hbase-client
      dockerfile: Dockerfile
    env_file:
      - ./hbase-client/.env
    ports:
      - "8082:8082"
    restart: unless-stopped

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - hadoop
    ports:
      - "8081:8081"
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped


  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
