version: "3"

services:
  hbase-master:
    hostname: hbase-master
    container_name: hbase-master
    build:
      context: database
      dockerfile: Dockerfile
    networks:
      - database
    ports:
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "9095:9095"
      - "2181:2181"
      - "16010:16010"
    volumes:
      - ./database/dataMaster:/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - hbase-master
    networks:
      - database
      - backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped


  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  database:
  backend:
